[package]
name = "driving-tests-site"
version = "0.1.0"
authors = [
    "Sasha Yusuk <thepulticula@gmail.com>",
    "Igor Shashin <kshico123@gmail.com>"
]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.33"
rocket = "0.4.5"
diesel = "1.4"


[dependencies.rocket_contrib]
version = "0.4.5"
default-features = false
features = ["diesel_mysql_pool"]