[package]
name = "driving-tests-site"
version = "0.1.0"
authors = ["Sasha Yusuk <thepulticula@gmail.com>",
    "Igor Shashin <kshico123@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.5"