[package]
name = "driving-tests-site"
version = "0.1.0"
authors = [
    "Sasha Yusuk <thepulticula@gmail.com>",
    "Igor Shashin <kshico123@gmail.com>"
]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.33"
diesel = "1.4"
actix-web = "3.2.0"
log = "0.4.11"
simple_logger = "1.11.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0.77"
rsa = "0.3.0"
rand = "0.7.3"
hex = "0.4.2"
lazy_static = "1.4.0"


[dependencies.rocket_contrib]
version = "0.4.5"
default-features = false
features = ["diesel_mysql_pool"]
